### ISSUE TITLE
Email verification on account sign up

### ISSUE THREAD

**Issue by andrewnoyes** [unfrl/carpool#19]
# Overview
In order to prevent fake email accounts on sign up, the user should be sent an email with a verification link.

# Implementation notes
* Will want an additional table for tracking user IDs and verification tokens
* User table should be updated to include a boolean `isVerified` that defaults to false
* Verification tokens should be generated using a library like [crypto-random-string](https://github.com/sindresorhus/crypto-random-string)
* The verification link sent in the email should roughly be in the form {hostUrl}/verify?token={verificationToken}&email={userEmail}
* Will need another controller/endpoint that processes the verification: 
  * If the token is found, then user's `isVerified` boolean should be flipped to true
  * If it is not found, either expired or invalid, then an appropriate status code should be returned to the client
* Verification tokens should expire - easy implementation could be to periodically run a job that deletes tokens that are older than a day (or whatever amount of time seems appropriate)
* For sending emails, a library like [nodemailer](https://nodemailer.com/about/) should be used

**Comment by MattInternet** [comment]
This could benefit from using Redis just because we could add auto-expiring keys and then the verification would be really fast/simple (just checking to see if the key is still present in the Redis instance). I'm not sure this feature alone justifies having a Redis instance, but if there are others that could benefit from having one (like caching requests or some pub/sub stuff) then it might be nice to just add it now and get it over with.

**Comment by MattInternet** [comment]
Also Im gonna pull out the email service implementation into another issue.
